<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>QA_Test</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>7b081f5e-12c1-46c9-a4f7-c1892be3d6dd</testSuiteGuid>
   <testCaseLink>
      <guid>34693821-7093-4142-a314-add7322a7db2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/TC1_Create_An_Item</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14c776dc-630e-4cd0-822d-d5f340272965</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b164c3e-6da5-492b-9367-8aa83d0e67e4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a2119949-5860-4204-bda8-4380cb861aad</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/TC2_Edit_Another_Existing_Item</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afc290ca-5627-4a04-80cf-bc8494071e6f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ab23c156-eb0a-4f50-96ef-8452af493f71</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/TC3_Delete_The_Item_Created</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14c776dc-630e-4cd0-822d-d5f340272965</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b164c3e-6da5-492b-9367-8aa83d0e67e4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>23643243-85aa-4a78-981e-b80a263993dc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC4_Check_Max_Long_In_Description</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>818a2ed7-0f15-4b3c-84f7-4eca994ebc36</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>17b37f5b-b9d6-437a-8e1a-5642c983ac5a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC4_Check_Max_Long_In_Description</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>818a2ed7-0f15-4b3c-84f7-4eca994ebc36</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
