<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>QA_Test</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>b522232a-124b-438f-b9b8-6aca15357dc8</testSuiteGuid>
   <testCaseLink>
      <guid>d545f9cf-61d9-4616-9f34-2be5c9f08f13</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC1_Create_An_Item</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14c776dc-630e-4cd0-822d-d5f340272965</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b164c3e-6da5-492b-9367-8aa83d0e67e4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>73281459-3b70-46b1-b931-c1e3f9e5980f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC2_Edit_Another_Existing_Item</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afc290ca-5627-4a04-80cf-bc8494071e6f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>437673f2-d74b-4208-92ea-b3d9359ecb8c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC3_Delete_The_Item_Created</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14c776dc-630e-4cd0-822d-d5f340272965</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b164c3e-6da5-492b-9367-8aa83d0e67e4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>344da193-7efc-4437-9fb8-97d6b9d3d89c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC4_Check_Max_Long_In_Description</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>818a2ed7-0f15-4b3c-84f7-4eca994ebc36</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a925bf78-84b5-4694-b24f-0ce160a1d1c2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/TC5_Check_If_Exists_In_The_List_The_Item_With_Text</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b47fa502-e2cd-4c46-a820-34aa21762e54</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
